### ISSUE TITLE
Great Apple interface article you wrote

### ISSUE THREAD

**Issue by BaronRK** [jessesquires/jessesquires.github.io#11]
http://www.jessesquires.com/adaptive-user-interfaces/

I linked to it for my art director.

You wrote "Finally, I should note that iOS 8 also provides an unspecified size class, which essentially means any size class. In other words, an unspecified size class means that a view should always display and behave the same way, regardless of other UI elements or the current device."

I offered him what I hope is a great example of this that you might want to add to your article.  A Phone Number Pad.  This is a UI element most people want to be about the same size no matter the display (iPhone 4 -> iPad largest) as it is a simulator for a physical thing for a human hand.

**Comment by jessesquires** [comment]
Thanks @BaronRK ! :smile:
