### ISSUE TITLE
Mention SwiftGen and Shark in "Namespaced constants in Swift" article

### ISSUE THREAD

**Issue by AliSoftware** [jessesquires/jessesquires.github.io#12]
Like Lee Morgan and its AutoAssets you mentioned in your article, others developed tools to generate constants automatically, which could be worth mentioning as well

* I personally developed [SwiftGen](https://github.com/AliSoftware/SwiftGen) which generates enums as constants for Image Assets, but also for Storyboards, UIColors… and even Localizable.strings. See [my related blog article here](http://alisoftware.github.io/swift/enum/constants/2015/07/19/enums-as-constants/).
* @kaandedeoglu developed [Shark](https://github.com/kaandedeoglu/Shark), which has a similar purpose (only dedicated to UIImages, but which adds some hierarchical structure to the constants)

**Comment by kaandedeoglu** [comment]
Thank you @AliSoftware for bringing this up and mentioning my project. I just want to include two more similar projects that I've seen around.

1: [Misen](https://github.com/tasanobu/Misen) by @tasanobu
2:[R.swift](https://github.com/mac-cain13/R.swift) by @mac-cain13

**Comment by DarthMike** [comment]
There's also [swiftrsrc](https://github.com/indragiek/swiftrsrc) by @indragiek

**Comment by jessesquires** [comment]
Thanks all! :smile:
