### ISSUE TITLE
Optionals With Core Data

### ISSUE THREAD

**Issue by Frizlab** [jessesquires/jessesquires.github.io#15]
In this article http://www.jessesquires.com/better-coredata-models-in-swift/, you say non-optional values should be written as such (without question mark) in the generated Swift files.

I must disagree.
The _model_ says it is invalid for a given property to have a nil value saved in the persistent store. However, it is perfectly valid for an unsaved entity to have a nil value! (If it has just been created for instance.) Even though it _should_ most of the time not happen.

These properties should be of type "optional but generally not nil," aka. the type followed by an exclamation point.

Your example would then become:

```swift
class Employee: NSManagedObject {

    @NSManaged var address: String?
    @NSManaged var dateOfBirth: NSDate!
    @NSManaged var email: String?

    @NSManaged var firstName: String!
    @NSManaged var lastName: String!
    @NSManaged var middleName: String?
   
    @NSManaged var salary: NSDecimalNumber
    @NSManaged var status: Int32
}
```

**Comment by jessesquires** [comment]
Hey @Frizlab :smile: 

>However, it is perfectly valid for an unsaved entity to have a nil value!

This is correct, but we solve this by using designated initializers for our model objects such that this cannot happen. See [Using Core Data in Swift](http://www.jessesquires.com/using-core-data-in-swift/).

**Comment by Frizlab** [comment]
Clever 😊
Though this solution only works when you can know the value for the properties at init time.
I think there are situations where you can’t and the “optional but generally not nil” solution should be considered.

Here’s an example.
Let’s say I fetch my objects from an API. Here’s a rough algorithm I would use to insert the objects in CoreData (for the sake of simplicity, our API can only send objects that contains “simple” properties, no relationships):
   - Start retrieving objects for entity `EntityName` (`EntityName` can be any valid CoreData entity for our model);
   - Network call + JSON parsing from API and get an array of dictionaries, representing the fetched objects;
   - For each JSON object retrieved, map the API properties to the CoreData properties name and create a new array of dictionaries, each representing one `EntityName`
   - For each of my `EntityName` dictionaries, insert a new entity `EntityName` in Core Data and set the properties from the dictionary (`setValuesForKeysWithDictionary()`)

As you can see, my parser cannot call a different initializer for each entity I have in the model. It would be a lot of duplicated code for nothing.
And I don’t think it would be possible to create an `initWithDictionary()` initializer either, because the only way to set the values of the properties would be to call `setValueForKey()` or an equivalent, but you cannot use `self` until you’re initialized.
