### ISSUE TITLE
BUG WITH SCROLLVIEW AND CONTENT SIZE

### ISSUE THREAD

**Issue by AlphazellaLevallois** [jessesquires/jessesquires.github.io#16]
I'm using JSQMessageVC, But this cause a bug in my app. when i push JSQMessageVC, the content size of a scrollview in the parentVC change ... 
Before :  
 myScrollview.contentSize = 1000, 375

And after 

myScrollview.contentSize = 2.5, 750.0

Do you know why?
JSQMessageVC cause a bug in all scrollview size in my app....

Thanks!

**Comment by jessesquires** [comment]
Hey @AlphazellaLevallois :smile: -- I think you have the wrong repo
