### ISSUE TITLE
Can you authorize us to translate your Open Source Swift series into Chinese?

### ISSUE THREAD

**Issue by numbbbbb** [jessesquires/jessesquires.github.io#19]
Hello Jesse,

I'm Jie Liang, you can call me Jie if you like.

Last year I organized a group of people to translate Apple's The Swift Programming Language into Chinese, in order to help many Chinese developers who cannot read english learn Swift. If you want to learn more please [read this](http://www.bloomberg.com/news/articles/2015-08-06/chinese-coders-translate-apple-s-ios-programming-language). Apple has added our translation into swift.org.

You know Chinese developers cannot access many websites(like twitter) and many of them cannot read english. So I found a non-profit translate group to help them.

Our group have 20+ people. All of us are iOS developers and we want to translate articles and publish them for free(http://swift.gg). All of our translations have gain the authorization from author. Our goal is helping Chinese iOS developers learn Swift well.

I found your Open Source Swift series really helpful, but I don't want infringement(while many others do). So I write this email to see whether you can authorize us.

We really want to do some useful things for others. We love Swift and we love coding.

We promise:
- All of our translations will be permanent free
- We will write your article's link and your name in the beginning of our translations

Would you like to help us?

Thanks.

**Comment by jessesquires** [comment]
Hey @numbbbbb ! :smile: 

This sounds great to me! Please feel free to publish the translated versions. :+1:

**Comment by numbbbbb** [comment]
Thanks Jesse! I will send you the translation link!

**Comment by Cee** [comment]
👍 Cool :)

**Comment by numbbbbb** [comment]
The translation of #0 has been published: [Open Source Swift #0](http://swift.gg/2015/12/29/swift-open-source/)

**Comment by jessesquires** [comment]
Hey @numbbbbb! :smile:

I've given the weekly newsletter a proper home: https://github.com/SwiftWeekly/swiftweekly.github.io

Future posts will happen there. Please [open as issue](https://github.com/SwiftWeekly/swiftweekly.github.io/issues/new) at the new repo and we can discussion future translations!
