### ISSUE TITLE
Missing final code in post - Avoiding the overuse of @objc in Swift

### ISSUE THREAD

**Issue by kvaidya** [jessesquires/jessesquires.github.io#26]
Improvement request - Also show the final code for NavigationItemConfigurable extension so that it is clearer by just looking at the code - Add  - 
```
extension NavigationItemConfigurable where Self: UIViewController {
  func configureNavigationItem() {
    navigationItem.leftBarButtonItem = UIBarButtonItem(
      barButtonSystemItem: .Cancel,
      target: self,
      action: #selector(didTapCancelButton(_:)))
  }
}

```
TO be clear it is mentioned - "Our previous extension on ViewControllerType can move to NavigationItemConfigurable instead" - but folks tend to look at the code snippet first and it is not included there

**Comment by jessesquires** [comment]
Thanks @kvaidya ! I'll update the post, unless you would like to submit a pull request 😄
