### ISSUE TITLE
Question: versioning of swift documentation

### ISSUE THREAD

**Issue by benrudhart** [jessesquires/jessesquires.github.io#27]
Hi Jesse,
I read your [blog post](http://www.jessesquires.com/swift-documentation/) on swift documentation using GitHub pages. I really like it - great ideas and a great tutorial.

I have one question left regarding the documentation: Do you have any ideas/ recommendations how to handle different versions of the documentations for your repos?
Ben

**Comment by jessesquires** [comment]
Thanks @benrudhart ! 😄 

That's a great question. This is one thing that CocoaDocs does really well.

You could follow the same approach that I outline in the post for your most recent docs, published at `username.github.io/library/`. Then, each time you release a new version, you could stash those docs in a subdirectory and then regenerate docs for the latest version. I'm not sure if you could automate this -- probably not, but you wouldn't need to do it very often.

Something like this:

- `username.github.io/library/`: latest version
- `username.github.io/library/1.0/` : for version 1
- `username.github.io/library/2.0/` : for version 2
- `username.github.io/library/2.3/` : for version 2.3
- etc

--------------------------------------------

I only publish the latest version of my docs to keeps things simpler, but version control allows people to find previous versions if they really need to.

**Comment by benrudhart** [comment]
Thank you for these helpful ideas!
