### ISSUE TITLE
My app keeps crashing

### ISSUE THREAD

**Issue by thehorbach** [jessesquires/jessesquires.github.io#29]
Hello.

I build a chat app using JSQMessagesViewController powered by Firebase. My text bubbles are being are working perfectly fine, however after I add a photo message and it has been displayed, I try to add a new text message and the app crashes on "finishSendingMessage()".

Please help :)

![screen shot 2016-07-29 at 13 58 26](https://cloud.githubusercontent.com/assets/16654641/17263519/610c2bf2-5596-11e6-9b4b-a39eb83933b8.png)
![screen shot 2016-07-29 at 13 58 14](https://cloud.githubusercontent.com/assets/16654641/17263518/610b4a0c-5596-11e6-96f5-c1909cd5c35d.png)
![screen shot 2016-07-29 at 13 56 57](https://cloud.githubusercontent.com/assets/16654641/17263520/610c6694-5596-11e6-820f-6eb8d7a07172.png)

**Comment by jessesquires** [comment]
You have the wrong repo. 😄 

Open an issue on JSQMessagesViewController.

**Comment by thehorbach** [comment]
Yeah, sorry, btw I send you an email :)
