### ISSUE TITLE
Objective-C switches

### ISSUE THREAD

**Issue by Panajev** [jessesquires/jessesquires.github.io#32]
It’s even worse in Objective-C — there are no errors or warnings for incomplete switch statements --> there are actually although they used to be  hidden in -Weverything and maybe still are :). -Weverything, clang diagnostic, and warning flags are your friend :).

**Comment by Panajev** [comment]
They are actually annoying for some people as they do not let you use default :).

**Comment by Panajev** [comment]
But you did address it a line further down :/. Sorry

**Comment by jessesquires** [comment]
👍  😄
