### ISSUE TITLE
Amen to that

### ISSUE THREAD

**Issue by dumbledad** [jessesquires/jessesquires.github.io#37]
I wish I'd read your article before upgrading to Swift 3. You say "resist doing any other refactoring during the migration". Instead I took the opportunity to move lots of methods into a more logical order, which has made merging or rebasing with other work branches extremely painful :-(

I also was not expecting that all my button relationships in my storyboard would be broken by the code changes and require redoing.

http://www.jessesquires.com/migrating-to-swift-3/

**Comment by jessesquires** [comment]
😄 thanks for the comments @dumbledad ! 😄 

hope your migration ends up ok.
