### ISSUE TITLE
Your jazzy post

### ISSUE THREAD

**Issue by grosch** [jessesquires/jessesquires.github.io#40]
Jesse,

thanks for the post on Jazzy documentation.  I just added that to my [ExpandableDatePicker](https://github.com/GargoyleSoft/ExpandableDatePicker) project.  You should obviously use it because it's awesome :)

Anyways, you mentioned that github will automatically publish that documentation now, but if I go to that repository I don't see where it's actually published.

**Comment by jessesquires** [comment]
Thanks @grosch ! 😄 

The project URLs are the same as the old gh-pages `<username>.github.io/<project>`, so it would be:
http://gargoylesoft.github.io/ExpandableDatePicker

There's also a repo setting that the owner will have to enable. (Current that page shows a 404)

**Comment by jessesquires** [comment]
In the settings, you'll see a section like this:

<img width="770" alt="screen shot 2017-01-09 at 3 40 51 pm" src="https://cloud.githubusercontent.com/assets/2301114/21788187/0da01a1a-d682-11e6-9ea0-2a97c3713ee5.png">

I have a custom domain setup, so it's slightly different.
