### ISSUE TITLE
[Refactoring singletons in Swift] UIViewController has non-UIKit dependencies

### ISSUE THREAD

**Issue by crcapps** [jessesquires/jessesquires.github.io#44]
That should never happen.  A UIViewController should never have a dependency that isn't A. A UIKit object or B. Its Delegate or Datasource.  There are no other dependencies to inject into a VC.

**Comment by jessesquires** [comment]
Thanks @crcapps ! 😄 

I think this would be difficult to achieve. I've never seen an app successfully do this.

**Comment by crcapps** [comment]
I do it all the time, for really complex stuff!  Think about how React/Redux and the MVVM pattern work, and what that means in the context of Swift's value semantics-oriented design.  What's the responsibility of a VC?  To render views and receive user input.  You just have to be very conscious of staying away from two-way databinding.

**Comment by jessesquires** [comment]
Ah right.

I guess what I meant was — you'll always have these non-UIKit elements as *transitive* dependencies. I don't really see a way around that, but good points. Then injecting fakes, etc. would make testing VCs even easier.

**Comment by crcapps** [comment]
Yeah, but keep in mind that the dependency graph doesn't cross service boundaries, and making service calls are what the delegate is for.

**Comment by crcapps** [comment]
One of the things is, when you talk about injecting dependencies into a class with a well-defined responsibility, you have to keep in mind that constructor creep is a very real thing and is toxic to programming to contract and that courier is an anti pattern.  Moving those dependencies "outward" as far as possible is a very good way to combat that- just receiving a delegate as a completely-constructed object and that being everything the class needs to perform its responsibility is a good thing.

Also, a side remark regarding DI and testability is that having a convenience constructor for testing is one thing, but well planned lazy defaults aren't dependency hiding at all, it's just convenience for the consumer to have as few parameters in a constructor as possible.  Sometimes Property Injection is the way to go!  Constructor or property injection aside, if it's necessary to break encapsulation for the sake of testability it's the smell of a pathological class hierarchy.

**Comment by crcapps** [comment]
These aren't a wall of accusations aimed at anyone, it's just a thing for people for whom Dependency injection is a new subject to keep in mind lest the constructor gets carried away and the VC is thousands of lines.
