### ISSUE TITLE
[Refactoring singletons in Swift] Singletons inside of the app

### ISSUE THREAD

**Issue by AndreiVidrasco** [jessesquires/jessesquires.github.io#45]
Hi Jesse,

I saw your article http://www.jessesquires.com/refactoring-singletons-in-swift/

Nice, I liked.

But singletons are nice because they're really easy to use. Creating dependency injection for each use of singletons will make them much more hard to use.
So, I suggest different idea. To create a new singleton. AppEnviroment.
He will keep references to all singletons used across the app.

I created a gist with raw implementation.
https://gist.github.com/AndreiVidrasco/7469e573934f7fe16cdbd1e72c8474c1

Can you check out and say what do you think?

Thanks,
Andrei

**Comment by jessesquires** [comment]
Thanks @AndreiVidrasco ! 👍 

Yeah -- that could work to make it easier to use. Although, I would inject the `AppEnvironment`:

```swift
class ClassA { //singleton use
    func method(_ appEnv: AppEnviroment = .shared) {
        appEnv.singletonA.printSelf()
    }
}
```

One thing to watch out for is if `AppEnvironment` gets too large.

**Comment by AndreiVidrasco** [comment]
The idea with App Environment I was in kickstarter project.

https://github.com/kickstarter/ios-oss/blob/master/Library/AppEnvironment.swift

For project like kickstarter, it's still manageable, so I don't think it could get too large

**Comment by kiliankoe** [comment]
What about moving the singleton to a protocol extension and inject it from there?

```swift
protocol UsesSingleton {
    var singleton: Singleton { get }
}

extension UsesSingleton {
    var singleton: Singleton {
        return Singleton.shared
    }
}
```

Then I can just do the following.

```swift
class SomeClass: UsesSingleton {
    func dowhatever() {
        singleton.whatever
    }
}
```

Not quite sure if it's a good idea or not to declare protocols like `UsesUserDefaults` or `UsesURLSession` (a better name might also come in handy), but it would leave the classes very clean. The only downside I can come up with is that I can only swap out the singleton for every user of it at once. But I guess that depends on my usage to possibly be a bad idea.

**Comment by jessesquires** [comment]
Thanks @kiliankoe ! 😄 Yeah, I could see this pattern being useful too
