### ISSUE TITLE
[Failable Initializers] Init? Possible Case

### ISSUE THREAD

**Issue by danielgomezrico** [jessesquires/jessesquires.github.io#8]
Hi

You say that is better not to use it because may be more dirty... but there are places where it make sence like make an init of an object with a JSON, so if the json don't have the requirements attributes... it will return a nil object.

You can extend the object class with the `init?(json: JSON)` constructor in your own class that make the request and just call that constructor with an `if let myObject = MyObject(json) {}`.

What do you think?

**Comment by jessesquires** [comment]
Hey @danielgomezrico - sure that's possible :smile: However, I think there are other improvements to make in this scenario.

I would argue that you should be validating your JSON elsewhere and initializing that object with all of its parameters explicitly defined (i.e. use Dependency Injection).

Initializing an object with JSON hides a lot of what's going on. That object knows about *everything*. It knows what JSON is, it knows how to parse it, etc. An object shouldn't know any of that.

We can make single-purpose objects for each step of this process, and unit-test them individually.

````swift
struct MyObject {
    let name: String
    let number: Int
    let date: NSDate

    init(name: String, number: Int, date: NSDate) {
        self.name = name;
        self.number = number
        self.date = date
    }
}

// some kind of JSON object
struct JSON {
    init() { }
}

struct JSONValidator {

    init() { }

    func isValid(json: JSON) -> Bool {
        // validate that json has all required attributes for MyObject
        return true
    }
}

struct MyObjectParser {
    let validator: JSONValidator

    init(validator: JSONValidator) {
        self.validator = validator
    }

    func parseMyObjectFromJSON(json: JSON) -> MyObject? {
        if (!validator.isValid(json)) {
            return nil
        }

        // parse the JSON to construct MyObject...

        return MyObject(name: "", number: 0, date: NSDate())
    }
}
````

Then we would use it like this:

````swift
let json = JSON() // some json from somewhere

let parser = MyObjectParser(validator: JSONValidator())

if let myObject = parser.parseMyObjectFromJSON(json) {
    // parsing succeeded
}
else {
    // parsing failed
}
````

There we go. No need for a failable initializer anywhere.

**Comment by danielgomezrico** [comment]
Opa, that looks great, thanks!

**Comment by jessesquires** [comment]
:+1:
