### ISSUE TITLE
Swift, Core Data, and unit testing - NSEntityDescription bug alternative work around

### ISSUE THREAD

**Issue by AliBeadle** [jessesquires/jessesquires.github.io#9]
Thanks for your blog that helped me find this - but here is an alternative approach to this problem on Stack Exchange that avoids making lots if things public:

http://stackoverflow.com/a/26795795/2466193

(Credit, of course, to the SO poster, not me who just found it!)

**Comment by jessesquires** [comment]
Thanks @AliBeadle !

Yep, I'm aware of and saw similar workarounds prior to writing the blog post.

I think this is actually a *terrible* idea. By doing this, you are building in a lot of assumptions and fragile logic into your core data stack. I wouldn't recommend doing this! :smile: 

Furthermore, your core data model *should* be in its own module anyway, and then the name-spacing issues are gone completely.

We know that Apple is aware of and working on the issues regarding testing and Swift, so this could change at any time.

**Comment by AliBeadle** [comment]
OK, I see. Yes, putting Core Data in a separate module makes things tidier and avoids making a lot of unnecessary things public - which feels wrong to me. I can see why not putting workaround code into the Core Data stack is not a good idea too.

Thanks.
